### ISSUE TITLE
TrinityCore last rev.

### ISSUE THREAD

**Issue by lainimer** [BlackWolfsDen/Eluna-Grumboz-Guild-Warz#2]
Unknown column 'mindmg' in 'field list'
Plz update column Health_mod.

**Comment by BlackWolfsDen** [comment]
BOOST_NPC_GOB_item.sql was built on a Boost core Prior to the removal if min/max dmg .
I don't have a Boost core . I use Ace. so I can update it as you post errors.

**Comment by BlackWolfsDen** [comment]
BOOST_NPC_GOB_item.sql  was created for Boost prior to the removal of min/max dmg. I don't use Boost, my cores are Ace. if you send me a extracted creature entry from your db then I could line everything up and remove anything extra.

**Comment by BlackWolfsDen** [comment]
? Hello?

**Comment by BlackWolfsDen** [comment]
Closed due to No Response back.
