### ISSUE TITLE
I'm trying to use this fabulous script but I got few trouble

### ISSUE THREAD

**Issue by verawow** [BlackWolfsDen/Eluna-Grumboz-Guild-Warz#3]
I'm using latest trinitycore and TDB 3.3.5.60. There were some error on this TDB with your sql but I modified it to recent TDB table columns so it's fine for executed and got the confirmation msg when eluna loading finished like GUILD WARZ ver : 4.91 Loaded on TC console.
However, In game, when I tried to type '/guild commands' , that slash command '/guild ' forces to change to guild chat and I can't type for next words ('command') after '/guild ' because of that automatically changing. So I tried to change that /guild command to /guilds at help table on guild_warz_335 Database and changed 'guild' texts to 'guilds' in source file (.lua) but after logged in , There was nothing happened when I typed '/guilds commands' . 

How can I fix this?

**Comment by BlackWolfsDen** [comment]
ok the commands are tied to the guild chat channel so you have to use `/guild` channel.
you need to change everything you changed back to `guild` first now.

you must be in a guild for any command to work.

when you are in /guild channel can you type anything?

srry for the lateness lol the usual winter internet freezes lol

**Comment by BlackWolfsDen** [comment]
and thank you for choosing my Guild Plot System :D 

Game Master commands are only usable by players with GM tag on, and they must ofc be in a guild also.

**Comment by verawow** [comment]
It's fixed  with downgrading the core version and TDB 3.5.5.59. There were some changes with newest core version and TDB.. and it works great now!! I just need to translate it to our language :)  Thanks for this amazing idea and work!  This is what I really hope for World of Warcraft to have to choose! you are genius !

**Comment by BlackWolfsDen** [comment]
Thank you :D enjoy

**Comment by BlackWolfsDen** [comment]
Don't forget we have a wiki :D 
For the die-hard's who just love this  :D I have a C++ version ..$.. its faster , works the same as the Eluna version, but its still in beta mode :D
Slp13at420 [EmuDevs](EmuDevs.com)

**Comment by BlackWolfsDen** [comment]
i am so sorry for the late responce but i have just literally managed to get back into this email address . ms wouldnt ever send the veri code nor respond to emails I sent but anywho lol Thanks for the gleaming review :D and yes i saw WoW's and said what .. the... wheres the invasion ,.?.?.. wheres the blood,.?.?.. wheres the FUN!?!

There is a new expanded version out now `Rise of the Guild` its the cpp version found here --> https://community.trinitycore.org/topic/13347-cpp-grumboz-guild-warz-rise-of-the-guild/


________________________________
